# ~/.config/starship.toml

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000
continuation_prompt = "▶▶"

#format = """ $localip$directory$character """
# format = """$username$env_var$hostname$directory$character"""
format = """$username$env_var$hostname$directory"""

# move the rest of the prompt to the right
right_format = """$all"""

[character]
success_symbol = "[➜](green)"
# success_symbol = "[](white)"
error_symbol = "[✗](bold red)"

# Shows an icon that should be included by zshrc script based on the distribution or os
[env_var.STARSHIP_DISTRO]
format = '[$env_value](yellow)'
variable = "STARSHIP_DISTRO"

[localip]
ssh_only = false
format = '[$localipv4](white)'
#trim_at = ".companyname.com"
disabled = true

[hostname]
ssh_only = false
format = "[$hostname](light blue)" # [$ssh_symbol](bold purple)"
# trim_at = ".tomtiv.me"
disabled = false
# ssh_symbol ="🌏"


# Shows the username
[username]
style_user = "purple"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
show_always = true

[directory]
truncation_length = 15
truncation_symbol = "…/"
home_symbol = "  ~"
read_only_style = "bold red"
read_only = " "

[git_branch]
symbol = " "
format = "via [$symbol$branch]($style) "
# truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = " "
modified = " "
staged = '[++\($count\)](green)'
renamed = "襁 "
deleted = " "

[docker_context]
format = " [ $context](red) "
disabled = false

[nodejs]
format = "[  $version](bold green) "
disabled = false

[python]
symbol = " "
python_binary = "python3"
disabled = false

[ruby]
format = "via [ $version]($style) "
disabled = true
add_newline = true
command_timeout = 1000
continuation_prompt = "▶▶"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[status]
style = 'blue'
# symbol = '🔴 '
# success_symbol = '🟢 SUCCESS'
format = '[$symbol$signal_name$maybe_int]($style) '
# format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[sudo]
style = "196"
symbol = "💻"
disabled = true
