name: CI

on: [push, pull_request]

env:
  COLUMNS: 80

defaults:
  run:
    shell: bash
    working-directory: .

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install shellcheck -y
      - run: ./tests/shellcheck.sh
      - uses: actions/setup-node@v2
        with:
          node-version: "13"
      - run: npm install -g bats
      - run: ./dotbare finit -u https://github.com/kazhala/dotfiles.git
      - run: bats tests
      - run: rm -rf "$HOME"/.cfg
      - run: ./dotbare finit -y
      - run: bats tests
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: brew install shellcheck
      - run: ./tests/shellcheck.sh
      - run: brew install bats
      - run: ./dotbare finit -u https://github.com/kazhala/dotfiles.git
      - run: bats tests
      - run: rm -rf "$HOME"/.cfg
      - run: ./dotbare finit -y
      - run: bats tests
