name: tomtiv stdenv CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  build-job:
    runs-on: ubuntu-latest
    steps:
      # - name: "tomtiv build on push"
      - run: echo Hello $user.name

  # test-job:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: git
  #     - run: echo "Commit Number"

  # test-job2:
  #   runs-on: ubuntu-latest
  #   steps:
  #      - echo "This job tests something, but takes more time than test-job1."
  #      - echo "After the echo commands complete, it runs the sleep command for 20 seconds"
  #      - echo "which simulates a test that runs 20 seconds longer than test-job1"
  #      - sleep 20

  # deploy-prod:
  #   runs-on: ubuntu-latest
  #   steps:
  #   stage: deploy
  #   script:
  #     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  #   environment: production


# jobs:
#   ubuntu:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: sudo apt-get install shellcheck -y
#       - run: ./tests/shellcheck.sh
#       - uses: actions/setup-node@v2
#         with:
#           node-version: "13"
#       - run: npm install -g bats
#       - run: ./dotbare finit -u https://github.com/kazhala/dotfiles.git
#       - run: bats tests
#       - run: rm -rf "$HOME"/.cfg
#       - run: ./dotbare finit -y
#       - run: bats tests
#   macos:
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v2
#       - run: brew install shellcheck
#       - run: ./tests/shellcheck.sh
#       - run: brew install bats
#       - run: ./dotbare finit -u https://github.com/kazhala/dotfiles.git
#       - run: bats tests
#       - run: rm -rf "$HOME"/.cfg
#       - run: ./dotbare finit -y
#       - run: bats tests
